
services: 

  booking-frontend:
    build:
      context: ./booking-frontend
      dockerfile: docker/Dockerfile
    container_name: frontend
    ports:
      - 8080:8080

  booking-backend:
    build:
      context: ./booking-backend
      dockerfile: docker/Dockerfile
    container_name: backend
    depends_on:
      - mongodb
      - booking-frontend
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/booking-houses
    ports:
      - 3000:3000
    volumes:
      - "./backend-data:/app/uploads"

  mongodb:
    image: mongo:4.4.17-focal
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo-data:/data/db  
